flatpak install --system app.drey.Warp -y
flatpak install --system com.anydesk.Anydesk -y
flatpak install --system com.github.dail8859.NotepadNext -y
flatpak install --system com.github.huluti.Curtail -y
flatpak install --system com.github.IsmaelMartinez.teams_for_linux -y
flatpak install --system com.github.jmlich.geotagging -y
flatpak install --system com.github.kagami.boram -y
flatpak install --system com.github.muriloventuroso.pdftricks -y
flatpak install --system com.github.polymeilex.neothesia -y
flatpak install --system com.github.unrud.RemoteTouchpad -y
flatpak install --system com.github.xournalpp.xournalpp -y
flatpak install --system com.google.EarthPro -y
flatpak install --system com.rtosta.zapzap -y
flatpak install --system com.sireliah.Dragit -y
flatpak install --system com.vzhd1701.gridplayer -y
flatpak install --system com.warlordsoftwares.formatlab -y
flatpak install --system com.xnview.XnViewMP -y
flatpak install --system eu.betterbird.Betterbird -y
flatpak install --system fr.handbrake.ghb -y
flatpak install --system in.srev.guiscrcpy -y
flatpak install --system io.github.cboxdoerfer.FSearch -y
flatpak install --system io.github.dfandrich.gpscorrelate -y
flatpak install --system io.github.giantpinkrobots.flatsweep -y
flatpak install --system io.github.JakubMelka.Pdf4qt -y
flatpak install --system io.github.jean28518.Linux-Assistant -y
flatpak install --system io.github.najepaliya.kleaner -y
flatpak install --system io.github.onionware_github.onionmedia -y
flatpak install --system io.github.sigmasd.stimulator -y
flatpak install --system io.github.tdesktop_x64.TDesktop -y
flatpak install --system io.github.tntwise.REAL-Video-Enhancer -y
flatpak install --system io.github.vikdevelop.SaveDesktop -y
flatpak install --system io.github.yuki_iptv.yuki-iptv -y
flatpak install --system net.biniou.LeBiniou -y
flatpak install --system net.codeindustry.MasterPDFEditor -y
flatpak install --system net.meijn.onvifviewer -y
flatpak install --system net.natesales.Aviator -y
flatpak install --system net.sourceforge.VMPK -y
flatpak install --system no.mifi.losslesscut -y
flatpak install --system org.filezillaproject.Filezilla -y
flatpak install --system org.gnome.Calls -y
flatpak install --system org.gnome.gitlab.YaLTeR.VideoTrimmer -y
flatpak install --system org.msweet.htmldoc -y
flatpak install --system org.nanuc.Axolotl -y
flatpak install --system org.raspberrypi.rpi-imager -y
flatpak install --system org.strawberrymusicplayer.strawberry -y
flatpak install --system org.viking.Viking -y
flatpak install --system org.x.Warpinator -y
flatpak install --system page.codeberg.JakobDev.jdFlatpakSnapshot -y
flatpak install --system page.codeberg.JakobDev.jdReplace -y
flatpak install --system tv.kodi.Kodi -y
